### ISSUE TITLE
I had question about import dataset

### ISSUE THREAD

**Issue by dotorl127** [tyagi-iiitv/PointPillars#11]
is it importing dataset to train and prediction in once?

**Comment by tyagi-iiitv** [comment]
I'm not sure about your question, as of my understanding, the training happens inside point_pillars_training_run.py and prediction is done using point_pillars_prediction.py. Is this what you were asking?

**Comment by dotorl127** [comment]
No, What I want to say does not load dataset in every frame but seems to be loaded at once when prediction in point_pillars_prediction.py.

**Comment by scrouzet** [comment]
> No, What I want to say does not load dataset in every frame but seems to be loaded at once when prediction in point_pillars_prediction.py.

As I understand the data is handled with a generator (for training, and also for prediction, definition SimpleDataGenerator() imported from processors.py) that loads the data by batch. So no the dataset is not "loaded at once".
