### ISSUE TITLE
CMake Error at CMakeLists.txt:3

### ISSUE THREAD

**Issue by han1366** [tyagi-iiitv/PointPillars#29]
when I executed " python3 setup.py install",the follow error occurred.
CMake Error at CMakeLists.txt:3 (add_subdirectory):
The source directory

/home/user/myProject/PointPillars/pybind11
does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:4 (pybind11_add_module):
Unknown CMake command "pybind11_add_module".

-- Configuring incomplete, errors occurred!

how can i deal with it?

**Comment by dvrohan** [comment]
I am also getting this issue. How did you solve it?
